// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DlocksColumns holds the columns for the "dlocks" table.
	DlocksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "holder", Type: field.TypeUUID, Unique: true},
		{Name: "deadline", Type: field.TypeInt64},
	}
	// DlocksTable holds the schema information for the "dlocks" table.
	DlocksTable = &schema.Table{
		Name:       "dlocks",
		Columns:    DlocksColumns,
		PrimaryKey: []*schema.Column{DlocksColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DlocksTable,
	}
)

func init() {
}
