// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"github.com/itsabgr/dblock/ent/dlock"
	"github.com/itsabgr/dblock/ent/predicate"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DLockUpdate is the builder for updating DLock entities.
type DLockUpdate struct {
	config
	hooks    []Hook
	mutation *DLockMutation
}

// Where appends a list predicates to the DLockUpdate builder.
func (du *DLockUpdate) Where(ps ...predicate.DLock) *DLockUpdate {
	du.mutation.Where(ps...)
	return du
}

// SetDeadline sets the "deadline" field.
func (du *DLockUpdate) SetDeadline(i int64) *DLockUpdate {
	du.mutation.ResetDeadline()
	du.mutation.SetDeadline(i)
	return du
}

// SetNillableDeadline sets the "deadline" field if the given value is not nil.
func (du *DLockUpdate) SetNillableDeadline(i *int64) *DLockUpdate {
	if i != nil {
		du.SetDeadline(*i)
	}
	return du
}

// AddDeadline adds i to the "deadline" field.
func (du *DLockUpdate) AddDeadline(i int64) *DLockUpdate {
	du.mutation.AddDeadline(i)
	return du
}

// Mutation returns the DLockMutation object of the builder.
func (du *DLockUpdate) Mutation() *DLockMutation {
	return du.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (du *DLockUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, du.sqlSave, du.mutation, du.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (du *DLockUpdate) SaveX(ctx context.Context) int {
	affected, err := du.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (du *DLockUpdate) Exec(ctx context.Context) error {
	_, err := du.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (du *DLockUpdate) ExecX(ctx context.Context) {
	if err := du.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (du *DLockUpdate) check() error {
	if v, ok := du.mutation.Deadline(); ok {
		if err := dlock.DeadlineValidator(v); err != nil {
			return &ValidationError{Name: "deadline", err: fmt.Errorf(`ent: validator failed for field "DLock.deadline": %w`, err)}
		}
	}
	return nil
}

func (du *DLockUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := du.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(dlock.Table, dlock.Columns, sqlgraph.NewFieldSpec(dlock.FieldID, field.TypeString))
	if ps := du.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := du.mutation.Deadline(); ok {
		_spec.SetField(dlock.FieldDeadline, field.TypeInt64, value)
	}
	if value, ok := du.mutation.AddedDeadline(); ok {
		_spec.AddField(dlock.FieldDeadline, field.TypeInt64, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, du.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dlock.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	du.mutation.done = true
	return n, nil
}

// DLockUpdateOne is the builder for updating a single DLock entity.
type DLockUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DLockMutation
}

// SetDeadline sets the "deadline" field.
func (duo *DLockUpdateOne) SetDeadline(i int64) *DLockUpdateOne {
	duo.mutation.ResetDeadline()
	duo.mutation.SetDeadline(i)
	return duo
}

// SetNillableDeadline sets the "deadline" field if the given value is not nil.
func (duo *DLockUpdateOne) SetNillableDeadline(i *int64) *DLockUpdateOne {
	if i != nil {
		duo.SetDeadline(*i)
	}
	return duo
}

// AddDeadline adds i to the "deadline" field.
func (duo *DLockUpdateOne) AddDeadline(i int64) *DLockUpdateOne {
	duo.mutation.AddDeadline(i)
	return duo
}

// Mutation returns the DLockMutation object of the builder.
func (duo *DLockUpdateOne) Mutation() *DLockMutation {
	return duo.mutation
}

// Where appends a list predicates to the DLockUpdate builder.
func (duo *DLockUpdateOne) Where(ps ...predicate.DLock) *DLockUpdateOne {
	duo.mutation.Where(ps...)
	return duo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (duo *DLockUpdateOne) Select(field string, fields ...string) *DLockUpdateOne {
	duo.fields = append([]string{field}, fields...)
	return duo
}

// Save executes the query and returns the updated DLock entity.
func (duo *DLockUpdateOne) Save(ctx context.Context) (*DLock, error) {
	return withHooks(ctx, duo.sqlSave, duo.mutation, duo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (duo *DLockUpdateOne) SaveX(ctx context.Context) *DLock {
	node, err := duo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (duo *DLockUpdateOne) Exec(ctx context.Context) error {
	_, err := duo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (duo *DLockUpdateOne) ExecX(ctx context.Context) {
	if err := duo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (duo *DLockUpdateOne) check() error {
	if v, ok := duo.mutation.Deadline(); ok {
		if err := dlock.DeadlineValidator(v); err != nil {
			return &ValidationError{Name: "deadline", err: fmt.Errorf(`ent: validator failed for field "DLock.deadline": %w`, err)}
		}
	}
	return nil
}

func (duo *DLockUpdateOne) sqlSave(ctx context.Context) (_node *DLock, err error) {
	if err := duo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dlock.Table, dlock.Columns, sqlgraph.NewFieldSpec(dlock.FieldID, field.TypeString))
	id, ok := duo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DLock.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := duo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dlock.FieldID)
		for _, f := range fields {
			if !dlock.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dlock.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := duo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := duo.mutation.Deadline(); ok {
		_spec.SetField(dlock.FieldDeadline, field.TypeInt64, value)
	}
	if value, ok := duo.mutation.AddedDeadline(); ok {
		_spec.AddField(dlock.FieldDeadline, field.TypeInt64, value)
	}
	_node = &DLock{config: duo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, duo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dlock.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	duo.mutation.done = true
	return _node, nil
}
