// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"dblock/ent/dlock"
	"dblock/ent/predicate"
	"errors"
	"fmt"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeDLock = "DLock"
)

// DLockMutation represents an operation that mutates the DLock nodes in the graph.
type DLockMutation struct {
	config
	op            Op
	typ           string
	id            *string
	holder        *uuid.UUID
	deadline      *int64
	adddeadline   *int64
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*DLock, error)
	predicates    []predicate.DLock
}

var _ ent.Mutation = (*DLockMutation)(nil)

// dlockOption allows management of the mutation configuration using functional options.
type dlockOption func(*DLockMutation)

// newDLockMutation creates new mutation for the DLock entity.
func newDLockMutation(c config, op Op, opts ...dlockOption) *DLockMutation {
	m := &DLockMutation{
		config:        c,
		op:            op,
		typ:           TypeDLock,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withDLockID sets the ID field of the mutation.
func withDLockID(id string) dlockOption {
	return func(m *DLockMutation) {
		var (
			err   error
			once  sync.Once
			value *DLock
		)
		m.oldValue = func(ctx context.Context) (*DLock, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().DLock.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withDLock sets the old DLock of the mutation.
func withDLock(node *DLock) dlockOption {
	return func(m *DLockMutation) {
		m.oldValue = func(context.Context) (*DLock, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m DLockMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m DLockMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of DLock entities.
func (m *DLockMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *DLockMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *DLockMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().DLock.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetHolder sets the "holder" field.
func (m *DLockMutation) SetHolder(u uuid.UUID) {
	m.holder = &u
}

// Holder returns the value of the "holder" field in the mutation.
func (m *DLockMutation) Holder() (r uuid.UUID, exists bool) {
	v := m.holder
	if v == nil {
		return
	}
	return *v, true
}

// OldHolder returns the old "holder" field's value of the DLock entity.
// If the DLock object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DLockMutation) OldHolder(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHolder is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHolder requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHolder: %w", err)
	}
	return oldValue.Holder, nil
}

// ResetHolder resets all changes to the "holder" field.
func (m *DLockMutation) ResetHolder() {
	m.holder = nil
}

// SetDeadline sets the "deadline" field.
func (m *DLockMutation) SetDeadline(i int64) {
	m.deadline = &i
	m.adddeadline = nil
}

// Deadline returns the value of the "deadline" field in the mutation.
func (m *DLockMutation) Deadline() (r int64, exists bool) {
	v := m.deadline
	if v == nil {
		return
	}
	return *v, true
}

// OldDeadline returns the old "deadline" field's value of the DLock entity.
// If the DLock object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DLockMutation) OldDeadline(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDeadline is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDeadline requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDeadline: %w", err)
	}
	return oldValue.Deadline, nil
}

// AddDeadline adds i to the "deadline" field.
func (m *DLockMutation) AddDeadline(i int64) {
	if m.adddeadline != nil {
		*m.adddeadline += i
	} else {
		m.adddeadline = &i
	}
}

// AddedDeadline returns the value that was added to the "deadline" field in this mutation.
func (m *DLockMutation) AddedDeadline() (r int64, exists bool) {
	v := m.adddeadline
	if v == nil {
		return
	}
	return *v, true
}

// ResetDeadline resets all changes to the "deadline" field.
func (m *DLockMutation) ResetDeadline() {
	m.deadline = nil
	m.adddeadline = nil
}

// Where appends a list predicates to the DLockMutation builder.
func (m *DLockMutation) Where(ps ...predicate.DLock) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the DLockMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *DLockMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.DLock, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *DLockMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *DLockMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (DLock).
func (m *DLockMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *DLockMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.holder != nil {
		fields = append(fields, dlock.FieldHolder)
	}
	if m.deadline != nil {
		fields = append(fields, dlock.FieldDeadline)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *DLockMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case dlock.FieldHolder:
		return m.Holder()
	case dlock.FieldDeadline:
		return m.Deadline()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *DLockMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case dlock.FieldHolder:
		return m.OldHolder(ctx)
	case dlock.FieldDeadline:
		return m.OldDeadline(ctx)
	}
	return nil, fmt.Errorf("unknown DLock field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DLockMutation) SetField(name string, value ent.Value) error {
	switch name {
	case dlock.FieldHolder:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHolder(v)
		return nil
	case dlock.FieldDeadline:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDeadline(v)
		return nil
	}
	return fmt.Errorf("unknown DLock field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *DLockMutation) AddedFields() []string {
	var fields []string
	if m.adddeadline != nil {
		fields = append(fields, dlock.FieldDeadline)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *DLockMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case dlock.FieldDeadline:
		return m.AddedDeadline()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DLockMutation) AddField(name string, value ent.Value) error {
	switch name {
	case dlock.FieldDeadline:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddDeadline(v)
		return nil
	}
	return fmt.Errorf("unknown DLock numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *DLockMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *DLockMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *DLockMutation) ClearField(name string) error {
	return fmt.Errorf("unknown DLock nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *DLockMutation) ResetField(name string) error {
	switch name {
	case dlock.FieldHolder:
		m.ResetHolder()
		return nil
	case dlock.FieldDeadline:
		m.ResetDeadline()
		return nil
	}
	return fmt.Errorf("unknown DLock field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *DLockMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *DLockMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *DLockMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *DLockMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *DLockMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *DLockMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *DLockMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown DLock unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *DLockMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown DLock edge %s", name)
}
